import type { SystemDeviceDef } from "@/types";

// Built-in device palette. Each entry carries its own type / lanes / details
// (previously these were shared per-group templates). User-added devices layer
// on top at runtime via setCustomSystemDefs (see @/store/useCatalog);
// SYSTEM_DEVICES is the merged list the palette and drop handler read.
export const SYSTEM_BUILTIN: SystemDeviceDef[] = [
  { id: "src-resolume", cat: "VIDEO SOURCES", type: "SOURCE", name: "Resolume Mac Pro", out: ["video", "network"], details: { res: "3840×2160", fps: "60p" } },
  { id: "src-gx2c", cat: "VIDEO SOURCES", type: "SOURCE", name: "Disguise gx 2c", out: ["video", "network"], details: { res: "4K", fps: "60p" } },
  { id: "src-watchout", cat: "VIDEO SOURCES", type: "SOURCE", name: "Watchout Server", out: ["video", "network"], details: { res: "4K", outputs: "4" } },
  { id: "src-playback", cat: "VIDEO SOURCES", type: "SOURCE", name: "PlaybackPro Plus", out: ["video"], details: { res: "1920×1080", fps: "60p" } },

  { id: "cam-ue150", cat: "CAMERAS", type: "SOURCE", name: "Panasonic AW-UE150", out: ["video", "network"], details: { res: "1920×1080", fps: "60i" } },
  { id: "cam-fr7", cat: "CAMERAS", type: "SOURCE", name: "Sony FR7 PTZ", out: ["video"], details: { res: "3840×2160", fps: "60p" } },
  { id: "cam-cv503", cat: "CAMERAS", type: "SOURCE", name: "Marshall CV503", out: ["video"], details: { res: "1920×1080", fps: "60p" } },

  { id: "proc-sx40", cat: "PROCESSORS", type: "PROC", name: "Brompton SX40", in: ["video"], out: ["network"], details: { ports: "4×10GbE", load: "0%" } },
  { id: "proc-tessera", cat: "PROCESSORS", type: "PROC", name: "Brompton Tessera S8", in: ["video"], out: ["network"], details: { ports: "8×1GbE", load: "0%" } },
  { id: "proc-helios", cat: "PROCESSORS", type: "PROC", name: "Megapixel Helios", in: ["video"], out: ["network"], details: { ports: "8×10GbE", load: "0%" } },
  { id: "proc-z6", cat: "PROCESSORS", type: "PROC", name: "Colorlight Z6", in: ["video"], out: ["network"], details: { ports: "20×RJ45", load: "0%" } },

  { id: "mix-vmix", cat: "MIXERS", type: "MIXER", name: "vMix M4", in: ["video", "video"], out: ["video"], details: { inputs: "4×SDI", outputs: "2×SDI" } },
  { id: "mix-v160", cat: "MIXERS", type: "MIXER", name: "Roland V-160HD", in: ["video", "video"], out: ["video"], details: { inputs: "16×", outputs: "4×" } },
  { id: "mix-carbonite", cat: "MIXERS", type: "MIXER", name: "Ross Carbonite Ultra", in: ["video", "video"], out: ["video"], details: { inputs: "24×", outputs: "8×" } },
  { id: "mix-e2", cat: "MIXERS", type: "MIXER", name: "Barco E2 Gen2", in: ["video", "video"], out: ["video"], details: { inputs: "28×", outputs: "14×" } },

  { id: "rte-kumo", cat: "ROUTING", type: "ROUTER", name: "AJA Kumo 3232", in: ["video"], out: ["video"], details: { size: "32×32", signal: "3G-SDI" } },
  { id: "rte-lightware", cat: "ROUTING", type: "ROUTER", name: "Lightware MX2-16×16", in: ["video"], out: ["video"], details: { size: "16×16", signal: "HDMI 2.0" } },

  { id: "wall-led", cat: "DISPLAYS", type: "WALL", name: "LED Wall", in: ["network"], details: { panels: "—", res: "—" } },
  { id: "wall-proj", cat: "DISPLAYS", type: "WALL", name: "Projector", in: ["video"], details: { lumens: "20000", res: "4K" } },
  { id: "wall-lcd", cat: "DISPLAYS", type: "WALL", name: "LCD Display", in: ["video"], details: { size: "55in", res: "4K" } },

  { id: "aud-sd12", cat: "AUDIO", type: "AUDIO", name: "DiGiCo SD12", in: ["audio"], out: ["audio"], details: { channels: "96", aux: "24" } },
  { id: "aud-cl5", cat: "AUDIO", type: "AUDIO", name: "Yamaha CL5", in: ["audio"], out: ["audio"], details: { channels: "72", aux: "24" } },
  { id: "aud-dlive", cat: "AUDIO", type: "AUDIO", name: "Allen & Heath dLive", in: ["audio"], out: ["audio"], details: { channels: "128", aux: "64" } },
  { id: "aud-ulxd", cat: "AUDIO", type: "AUDIO", name: "Shure ULXD4Q", in: ["audio"], out: ["audio"], details: { channels: "4", band: "G50" } },

  { id: "amp-la12x", cat: "AMPLIFIERS", type: "AMP", name: "L-Acoustics LA12X", in: ["audio"], out: ["audio"], details: { ch: "4", w: "12.8kW" } },
  { id: "amp-plm", cat: "AMPLIFIERS", type: "AMP", name: "Lab.gruppen PLM 20K44", in: ["audio"], out: ["audio"], details: { ch: "4", w: "20kW" } },

  { id: "net-cisco", cat: "NETWORK", type: "NETWORK", name: "Cisco Cat 9300", in: ["network"], out: ["network"], details: { ports: "48×1GbE", uplink: "4×10G" } },
  { id: "net-gigacore", cat: "NETWORK", type: "NETWORK", name: "Luminex GigaCore 30i", in: ["network"], out: ["network"], details: { ports: "30×", uplink: "SFP+" } },
  { id: "net-arista", cat: "NETWORK", type: "NETWORK", name: "Arista 7050X", in: ["network"], out: ["network"], details: { ports: "32×100GbE", uplink: "—" } },

  { id: "pwr-distro", cat: "POWER", type: "POWER", name: "Distro 200A 3ϕ", out: ["power"], details: { capacity: "144kVA", load: "0kVA" } },
  { id: "pwr-lex", cat: "POWER", type: "POWER", name: "Lex SQ-12IL", out: ["power"], details: { capacity: "12×20A", load: "0A" } },
  { id: "pwr-ups", cat: "POWER", type: "POWER", name: "Eaton 9PX UPS", out: ["power"], details: { capacity: "5kVA", runtime: "12min" } },

  // ─── Blackmagic Design ───

  { id: "bmd-media-player-10g", cat: "VIDEO SOURCES", type: "SOURCE", name: "BMD Media Player 10G", in: ["network"], out: ["video"], details: { res: "Ultra HD", io: "10G IP" } },

  { id: "bmd-ursa-cine-12k", cat: "CAMERAS", type: "SOURCE", name: "BMD URSA Cine 12K", out: ["video", "network"], details: { res: "12K", codec: "BRAW" } },
  { id: "bmd-ursa-cine-17k", cat: "CAMERAS", type: "SOURCE", name: "BMD URSA Cine 65mm 17K", out: ["video", "network"], details: { res: "17K", codec: "BRAW" } },
  { id: "bmd-ursa-cine-immersive", cat: "CAMERAS", type: "SOURCE", name: "BMD URSA Cine Immersive", out: ["video", "network"], details: { res: "8K per eye", codec: "BRAW" } },
  { id: "bmd-pyxis-6k", cat: "CAMERAS", type: "SOURCE", name: "BMD PYXIS 6K", out: ["video"], details: { res: "6K", codec: "BRAW" } },
  { id: "bmd-pyxis-12k", cat: "CAMERAS", type: "SOURCE", name: "BMD PYXIS 12K", out: ["video"], details: { res: "12K", codec: "BRAW" } },
  { id: "bmd-ursa-mini-pro-12k", cat: "CAMERAS", type: "SOURCE", name: "BMD URSA Mini Pro 12K OLPF", out: ["video"], details: { res: "12K", codec: "BRAW" } },
  { id: "bmd-ursa-mini-pro-46k", cat: "CAMERAS", type: "SOURCE", name: "BMD URSA Mini Pro 4.6K G2", out: ["video"], details: { res: "4.6K", codec: "BRAW" } },
  { id: "bmd-ursa-broadcast-g2", cat: "CAMERAS", type: "SOURCE", name: "BMD URSA Broadcast G2", out: ["video"], details: { res: "3840×2160", fps: "60p" } },
  { id: "bmd-cinema-camera-6k", cat: "CAMERAS", type: "SOURCE", name: "BMD Cinema Camera 6K", out: ["video"], details: { res: "6K", codec: "BRAW" } },
  { id: "bmd-pocket-4k", cat: "CAMERAS", type: "SOURCE", name: "BMD Pocket Cinema Camera 4K", out: ["video"], details: { res: "4K", codec: "BRAW" } },
  { id: "bmd-pocket-6k-g2", cat: "CAMERAS", type: "SOURCE", name: "BMD Pocket Cinema Camera 6K G2", out: ["video"], details: { res: "6K", codec: "BRAW" } },
  { id: "bmd-pocket-6k-pro", cat: "CAMERAS", type: "SOURCE", name: "BMD Pocket Cinema Camera 6K Pro", out: ["video"], details: { res: "6K", codec: "BRAW" } },
  { id: "bmd-studio-4k-plus-g2", cat: "CAMERAS", type: "SOURCE", name: "BMD Studio Camera 4K Plus G2", out: ["video", "network"], details: { res: "3840×2160", fps: "60p" } },
  { id: "bmd-studio-4k-pro-g2", cat: "CAMERAS", type: "SOURCE", name: "BMD Studio Camera 4K Pro G2", out: ["video", "network"], details: { res: "3840×2160", fps: "60p" } },
  { id: "bmd-studio-6k-pro", cat: "CAMERAS", type: "SOURCE", name: "BMD Studio Camera 6K Pro", out: ["video", "network"], details: { res: "6K", codec: "BRAW" } },
  { id: "bmd-micro-studio-4k-g2", cat: "CAMERAS", type: "SOURCE", name: "BMD Micro Studio Camera 4K G2", out: ["video"], details: { res: "3840×2160", fps: "60p" } },
  { id: "bmd-camera-fiber-conv", cat: "CAMERAS", type: "CONV", name: "BMD Camera Fiber Converter", in: ["video"], out: ["video"], details: { in: "12G-SDI", out: "SMPTE fiber" } },
  { id: "bmd-studio-fiber-conv", cat: "CAMERAS", type: "CONV", name: "BMD Studio Fiber Converter", in: ["video"], out: ["video"], details: { in: "SMPTE fiber", out: "12G-SDI" } },
  { id: "bmd-studio-converter", cat: "CAMERAS", type: "CONV", name: "BMD Studio Converter", in: ["video"], out: ["video"], details: { in: "SMPTE fiber", out: "12G-SDI" } },

  { id: "bmd-atem-mini-pro", cat: "MIXERS", type: "MIXER", name: "BMD ATEM Mini Pro", in: ["video", "video"], out: ["video", "network"], details: { inputs: "4×HDMI", outputs: "1×HDMI" } },
  { id: "bmd-atem-mini-pro-iso", cat: "MIXERS", type: "MIXER", name: "BMD ATEM Mini Pro ISO", in: ["video", "video"], out: ["video", "network"], details: { inputs: "4×HDMI", outputs: "1×HDMI" } },
  { id: "bmd-atem-mini-extreme-g2", cat: "MIXERS", type: "MIXER", name: "BMD ATEM Mini Extreme ISO G2", in: ["video", "video"], out: ["video", "network"], details: { inputs: "8×HDMI", outputs: "3×HDMI" } },
  { id: "bmd-atem-sdi", cat: "MIXERS", type: "MIXER", name: "BMD ATEM SDI", in: ["video", "video"], out: ["video"], details: { inputs: "4×3G-SDI", outputs: "2×3G-SDI" } },
  { id: "bmd-atem-sdi-pro-iso", cat: "MIXERS", type: "MIXER", name: "BMD ATEM SDI Pro ISO", in: ["video", "video"], out: ["video", "network"], details: { inputs: "4×3G-SDI", outputs: "2×3G-SDI" } },
  { id: "bmd-atem-sdi-extreme-iso", cat: "MIXERS", type: "MIXER", name: "BMD ATEM SDI Extreme ISO", in: ["video", "video"], out: ["video", "network"], details: { inputs: "8×3G-SDI", outputs: "4×3G-SDI" } },
  { id: "bmd-atem-tvs-hd8", cat: "MIXERS", type: "MIXER", name: "BMD ATEM Television Studio HD8", in: ["video", "video"], out: ["video"], details: { inputs: "8×3G-SDI", outputs: "12×3G-SDI" } },
  { id: "bmd-atem-tvs-hd8-iso", cat: "MIXERS", type: "MIXER", name: "BMD ATEM Television Studio HD8 ISO", in: ["video", "video"], out: ["video"], details: { inputs: "8×3G-SDI", outputs: "12×3G-SDI" } },
  { id: "bmd-atem-tvs-4k8", cat: "MIXERS", type: "MIXER", name: "BMD ATEM Television Studio 4K8", in: ["video", "video"], out: ["video"], details: { inputs: "8×12G-SDI", outputs: "12×12G-SDI" } },
  { id: "bmd-atem-1me-4k", cat: "MIXERS", type: "MIXER", name: "BMD ATEM 1 M/E Constellation 4K", in: ["video", "video"], out: ["video"], details: { inputs: "10×12G-SDI", outputs: "6×12G-SDI" } },
  { id: "bmd-atem-2me-4k", cat: "MIXERS", type: "MIXER", name: "BMD ATEM 2 M/E Constellation 4K", in: ["video", "video"], out: ["video"], details: { inputs: "20×12G-SDI", outputs: "12×12G-SDI" } },
  { id: "bmd-atem-4me-4k", cat: "MIXERS", type: "MIXER", name: "BMD ATEM 4 M/E Constellation 4K", in: ["video", "video"], out: ["video"], details: { inputs: "40×12G-SDI", outputs: "28×12G-SDI" } },
  { id: "bmd-atem-4me-4k-plus", cat: "MIXERS", type: "MIXER", name: "BMD ATEM 4 M/E Constellation 4K Plus", in: ["video", "video"], out: ["video"], details: { inputs: "80×12G-SDI", outputs: "52×12G-SDI" } },
  { id: "bmd-atem-4me-ip", cat: "MIXERS", type: "MIXER", name: "BMD ATEM 4 M/E Constellation IP", in: ["network"], out: ["network"], details: { me: "4 M/E", format: "ST 2110" } },
  { id: "bmd-atem-4me-ip-plus", cat: "MIXERS", type: "MIXER", name: "BMD ATEM 4 M/E Constellation IP Plus", in: ["network"], out: ["network"], details: { me: "4 M/E", format: "ST 2110" } },
  { id: "bmd-atem-constellation-8k", cat: "MIXERS", type: "MIXER", name: "BMD ATEM Constellation 8K", in: ["video", "video"], out: ["video"], details: { inputs: "40×12G-SDI", outputs: "24×12G-SDI" } },
  { id: "bmd-ultimatte-12-hd-mini", cat: "MIXERS", type: "KEYER", name: "BMD Ultimatte 12 HD Mini", in: ["video", "video"], out: ["video"], details: { format: "HD", sdi: "3G-SDI" } },
  { id: "bmd-ultimatte-12-hd", cat: "MIXERS", type: "KEYER", name: "BMD Ultimatte 12 HD", in: ["video", "video"], out: ["video"], details: { format: "HD", sdi: "3G-SDI" } },
  { id: "bmd-ultimatte-12-4k", cat: "MIXERS", type: "KEYER", name: "BMD Ultimatte 12 4K", in: ["video", "video"], out: ["video"], details: { format: "Ultra HD", sdi: "12G-SDI" } },
  { id: "bmd-ultimatte-12-8k", cat: "MIXERS", type: "KEYER", name: "BMD Ultimatte 12 8K", in: ["video", "video"], out: ["video"], details: { format: "8K", sdi: "12G-SDI" } },

  { id: "bmd-videohub-10x10", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub 10×10 12G", in: ["video"], out: ["video"], details: { size: "10×10", signal: "12G-SDI" } },
  { id: "bmd-videohub-20x20", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub 20×20 12G", in: ["video"], out: ["video"], details: { size: "20×20", signal: "12G-SDI" } },
  { id: "bmd-videohub-40x40", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub 40×40 12G", in: ["video"], out: ["video"], details: { size: "40×40", signal: "12G-SDI" } },
  { id: "bmd-videohub-80x80", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub 80×80 12G", in: ["video"], out: ["video"], details: { size: "80×80", signal: "12G-SDI" } },
  { id: "bmd-videohub-120x120", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub 120×120 12G", in: ["video"], out: ["video"], details: { size: "120×120", signal: "12G-SDI" } },
  { id: "bmd-videohub-mini-4x2", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub Mini 4×2 12G", in: ["video"], out: ["video"], details: { size: "4×2", signal: "12G-SDI" } },
  { id: "bmd-videohub-mini-6x2", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub Mini 6×2 12G", in: ["video"], out: ["video"], details: { size: "6×2", signal: "12G-SDI" } },
  { id: "bmd-videohub-mini-8x4", cat: "ROUTING", type: "ROUTER", name: "BMD Videohub Mini 8×4 12G", in: ["video"], out: ["video"], details: { size: "8×4", signal: "12G-SDI" } },
  { id: "bmd-videohub-cleanswitch", cat: "ROUTING", type: "ROUTER", name: "BMD Smart Videohub CleanSwitch 12×12", in: ["video"], out: ["video"], details: { size: "12×12", signal: "6G-SDI" } },

  { id: "bmd-hyperdeck-hd-mini", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Studio HD Mini", in: ["video"], out: ["video"], details: { format: "HD", codec: "ProRes/H.264" } },
  { id: "bmd-hyperdeck-hd-plus", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Studio HD Plus", in: ["video"], out: ["video"], details: { format: "HD", codec: "ProRes/H.264" } },
  { id: "bmd-hyperdeck-hd-pro", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Studio HD Pro", in: ["video"], out: ["video"], details: { format: "HD", codec: "ProRes/H.264" } },
  { id: "bmd-hyperdeck-4k-pro", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Studio 4K Pro", in: ["video"], out: ["video"], details: { format: "Ultra HD", codec: "ProRes/H.265" } },
  { id: "bmd-hyperdeck-extreme-4k", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Extreme 4K HDR", in: ["video"], out: ["video"], details: { format: "Ultra HD", codec: "ProRes/H.265" } },
  { id: "bmd-hyperdeck-extreme-8k", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Extreme 8K HDR", in: ["video"], out: ["video"], details: { format: "8K", codec: "ProRes/H.265" } },
  { id: "bmd-hyperdeck-iso-100g", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck ISO Recorder 100G", in: ["network"], out: ["network"], details: { format: "Ultra HD", io: "100G IP" } },
  { id: "bmd-hyperdeck-shuttle-hd", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Shuttle HD", in: ["video"], out: ["video"], details: { format: "HD", codec: "ProRes/H.264" } },
  { id: "bmd-hyperdeck-shuttle-4k", cat: "RECORD & PLAYBACK", type: "REC", name: "BMD HyperDeck Shuttle 4K Pro", in: ["video"], out: ["video"], details: { format: "Ultra HD", codec: "ProRes/H.265" } },
  { id: "bmd-ultrastudio-express-rec", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD UltraStudio Express 3G Recorder", in: ["video"], out: ["video"], details: { bus: "Thunderbolt", format: "3G-SDI" } },
  { id: "bmd-ultrastudio-express-mon", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD UltraStudio Express 3G Monitor", in: ["video"], out: ["video"], details: { bus: "Thunderbolt", format: "3G-SDI" } },
  { id: "bmd-ultrastudio-hd-mini", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD UltraStudio HD Mini", in: ["video"], out: ["video"], details: { bus: "Thunderbolt 3", format: "3G-SDI" } },
  { id: "bmd-ultrastudio-4k-mini", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD UltraStudio 4K Mini", in: ["video"], out: ["video"], details: { bus: "Thunderbolt 3", format: "12G-SDI" } },
  { id: "bmd-intensity-pro-4k", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD Intensity Pro 4K", in: ["video"], out: ["video"], details: { bus: "PCIe", format: "HDMI/analog" } },
  { id: "bmd-decklink-4k-extreme", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD DeckLink 4K Extreme 12G", in: ["video"], out: ["video"], details: { bus: "PCIe", format: "12G-SDI" } },
  { id: "bmd-decklink-8k-pro-g2", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD DeckLink 8K Pro G2", in: ["video"], out: ["video"], details: { bus: "PCIe", format: "8K 12G-SDI" } },
  { id: "bmd-decklink-ip-hd", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD DeckLink IP HD", in: ["network"], out: ["network"], details: { bus: "PCIe", format: "ST 2110" } },
  { id: "bmd-decklink-ip-hd-optical", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD DeckLink IP HD Optical", in: ["network"], out: ["network"], details: { bus: "PCIe", format: "ST 2110 SFP" } },
  { id: "bmd-decklink-ip-sdi-hd", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD DeckLink IP/SDI HD", in: ["video", "network"], out: ["video", "network"], details: { bus: "PCIe", format: "ST 2110 + SDI" } },
  { id: "bmd-decklink-ip-100g", cat: "RECORD & PLAYBACK", type: "CAPTURE", name: "BMD DeckLink IP 100G", in: ["network"], out: ["network"], details: { bus: "PCIe", format: "100G ST 2110" } },

  { id: "bmd-micro-hdmi-sdi-3g", cat: "CONVERTERS", type: "CONV", name: "BMD Micro Converter HDMI to SDI 3G", in: ["video"], out: ["video"], details: { in: "HDMI", out: "3G-SDI" } },
  { id: "bmd-micro-sdi-hdmi-3g", cat: "CONVERTERS", type: "CONV", name: "BMD Micro Converter SDI to HDMI 3G", in: ["video"], out: ["video"], details: { in: "3G-SDI", out: "HDMI" } },
  { id: "bmd-micro-bidirect-3g", cat: "CONVERTERS", type: "CONV", name: "BMD Micro Converter BiDirectional SDI/HDMI 3G", in: ["video"], out: ["video"], details: { in: "SDI/HDMI", out: "SDI/HDMI" } },
  { id: "bmd-micro-hdmi-sdi-12g", cat: "CONVERTERS", type: "CONV", name: "BMD Micro Converter HDMI to SDI 12G", in: ["video"], out: ["video"], details: { in: "HDMI", out: "12G-SDI" } },
  { id: "bmd-micro-sdi-hdmi-12g", cat: "CONVERTERS", type: "CONV", name: "BMD Micro Converter SDI to HDMI 12G", in: ["video"], out: ["video"], details: { in: "12G-SDI", out: "HDMI" } },
  { id: "bmd-micro-bidirect-12g", cat: "CONVERTERS", type: "CONV", name: "BMD Micro Converter BiDirectional SDI/HDMI 12G", in: ["video"], out: ["video"], details: { in: "SDI/HDMI", out: "SDI/HDMI" } },
  { id: "bmd-mini-hdmi-sdi-6g", cat: "CONVERTERS", type: "CONV", name: "BMD Mini Converter HDMI to SDI 6G", in: ["video"], out: ["video"], details: { in: "HDMI", out: "6G-SDI" } },
  { id: "bmd-mini-sdi-hdmi-6g", cat: "CONVERTERS", type: "CONV", name: "BMD Mini Converter SDI to HDMI 6G", in: ["video"], out: ["video"], details: { in: "6G-SDI", out: "HDMI" } },
  { id: "bmd-mini-updowncross-hd", cat: "CONVERTERS", type: "CONV", name: "BMD Mini Converter UpDownCross HD", in: ["video"], out: ["video"], details: { in: "3G-SDI", out: "3G-SDI" } },
  { id: "bmd-teranex-mini-sdi-hdmi-12g", cat: "CONVERTERS", type: "CONV", name: "BMD Teranex Mini SDI to HDMI 12G", in: ["video"], out: ["video"], details: { in: "12G-SDI", out: "HDMI" } },
  { id: "bmd-teranex-mini-sdi-hdmi-8k", cat: "CONVERTERS", type: "CONV", name: "BMD Teranex Mini SDI to HDMI 8K HDR", in: ["video"], out: ["video"], details: { in: "Quad 12G-SDI", out: "HDMI 2.0" } },
  { id: "bmd-teranex-mini-sdi-dp-8k", cat: "CONVERTERS", type: "CONV", name: "BMD Teranex Mini SDI to DisplayPort 8K HDR", in: ["video"], out: ["video"], details: { in: "Quad 12G-SDI", out: "DisplayPort" } },
  { id: "bmd-teranex-standards", cat: "CONVERTERS", type: "CONV", name: "BMD Teranex Standards Conversion", in: ["video"], out: ["video"], details: { in: "12G-SDI", out: "12G-SDI" } },
  { id: "bmd-2110-conv-3x3g", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Converter 3×3G", in: ["video"], out: ["network"], details: { in: "3×3G-SDI", out: "ST 2110" } },
  { id: "bmd-2110-sdi-hdmi-12g", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP SDI to HDMI 12G", in: ["network"], out: ["video"], details: { in: "ST 2110", out: "HDMI" } },
  { id: "bmd-2110-sdi-hdmi-12g-10", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP SDI to HDMI 12G-10", in: ["network"], out: ["video"], details: { in: "ST 2110 10G", out: "HDMI" } },
  { id: "bmd-2110-mini-ip-hdmi", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Mini IP to HDMI", in: ["network"], out: ["video"], details: { in: "ST 2110", out: "HDMI" } },
  { id: "bmd-2110-mini-ip-hdmi-sfp", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Mini IP to HDMI SFP", in: ["network"], out: ["video"], details: { in: "ST 2110 SFP", out: "HDMI" } },
  { id: "bmd-2110-mini-bidirect", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Mini BiDirect 12G", in: ["video", "network"], out: ["video", "network"], details: { in: "12G-SDI/IP", out: "12G-SDI/IP" } },
  { id: "bmd-2110-mini-bidirect-sfp", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Mini BiDirect 12G SFP", in: ["video", "network"], out: ["video", "network"], details: { in: "12G-SDI/IP", out: "SFP" } },
  { id: "bmd-2110-conv-4x12g", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Converter 4×12G PWR", in: ["video"], out: ["network"], details: { in: "4×12G-SDI", out: "ST 2110" } },
  { id: "bmd-2110-conv-8x12g-sfp", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Converter 8×12G SFP", in: ["video"], out: ["network"], details: { in: "8×12G-SDI", out: "ST 2110 SFP" } },
  { id: "bmd-2110-updowncross-12g", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP UpDownCross 12G", in: ["network"], out: ["network"], details: { in: "ST 2110", out: "ST 2110" } },
  { id: "bmd-2110-presentation", cat: "CONVERTERS", type: "CONV", name: "BMD 2110 IP Presentation Converter", in: ["video"], out: ["network"], details: { in: "HDMI/SDI", out: "ST 2110" } },
  { id: "bmd-studiobridge-10g", cat: "CONVERTERS", type: "CONV", name: "BMD StudioBridge 10G PWR", in: ["network"], out: ["video"], details: { in: "10G IP", out: "12G-SDI" } },
  { id: "bmd-studiobridge-100g", cat: "CONVERTERS", type: "CONV", name: "BMD StudioBridge 100G", in: ["network"], out: ["video"], details: { in: "100G IP", out: "12G-SDI" } },
  { id: "bmd-sdi-expander-8x12g", cat: "CONVERTERS", type: "CONV", name: "BMD SDI Expander 8×12G", in: ["network"], out: ["video"], details: { in: "ST 2110", out: "8×12G-SDI" } },
  { id: "bmd-updowncross-100g", cat: "CONVERTERS", type: "CONV", name: "BMD UpDownCross 100G", in: ["network"], out: ["network"], details: { in: "100G IP", out: "100G IP" } },

  { id: "bmd-smartview-4k-g3", cat: "MONITORING", type: "MON", name: "BMD SmartView 4K G3", in: ["video"], details: { size: "15.6in", format: "12G-SDI" } },
  { id: "bmd-smartview-duo", cat: "MONITORING", type: "MON", name: "BMD SmartView Duo", in: ["video"], details: { size: "2×8in", format: "3G-SDI" } },
  { id: "bmd-smartscope-duo-4k", cat: "MONITORING", type: "MON", name: "BMD SmartScope Duo 4K", in: ["video"], details: { size: "2×8in", format: "6G-SDI" } },
  { id: "bmd-multiview-4-hd", cat: "MONITORING", type: "MON", name: "BMD MultiView 4 HD", in: ["video"], out: ["video"], details: { views: "4", format: "3G-SDI" } },
  { id: "bmd-multiview-4", cat: "MONITORING", type: "MON", name: "BMD MultiView 4", in: ["video"], out: ["video"], details: { views: "4", format: "12G-SDI" } },
  { id: "bmd-multiview-16", cat: "MONITORING", type: "MON", name: "BMD MultiView 16", in: ["video"], out: ["video"], details: { views: "16", format: "12G-SDI" } },
  { id: "bmd-video-assist-5-3g", cat: "MONITORING", type: "MON", name: "BMD Video Assist 5 3G", in: ["video"], out: ["video"], details: { size: "5in", format: "3G-SDI" } },
  { id: "bmd-video-assist-7-3g", cat: "MONITORING", type: "MON", name: "BMD Video Assist 7 3G", in: ["video"], out: ["video"], details: { size: "7in", format: "3G-SDI" } },
  { id: "bmd-video-assist-5-12g", cat: "MONITORING", type: "MON", name: "BMD Video Assist 5 12G", in: ["video"], out: ["video"], details: { size: "5in", format: "12G-SDI" } },
  { id: "bmd-video-assist-7-12g", cat: "MONITORING", type: "MON", name: "BMD Video Assist 7 12G", in: ["video"], out: ["video"], details: { size: "7in", format: "12G-SDI" } },

  { id: "bmd-streaming-encoder-4k", cat: "STREAMING", type: "STREAM", name: "BMD Streaming Encoder 4K", in: ["video"], out: ["network"], details: { codec: "H.264/H.265", out: "SRT/RTMP" } },
  { id: "bmd-streaming-encoder-hd", cat: "STREAMING", type: "STREAM", name: "BMD Streaming Encoder HD", in: ["video"], out: ["network"], details: { codec: "H.264", out: "SRT/RTMP" } },
  { id: "bmd-streaming-decoder-4k", cat: "STREAMING", type: "STREAM", name: "BMD Streaming Decoder 4K", in: ["network"], out: ["video"], details: { codec: "H.264/H.265", out: "12G-SDI" } },
  { id: "bmd-atem-streaming-bridge", cat: "STREAMING", type: "STREAM", name: "BMD ATEM Streaming Bridge", in: ["network"], out: ["video"], details: { codec: "SRT/RTMP", out: "HDMI/SDI" } },

  { id: "bmd-atem-panel-10", cat: "CONTROL PANELS", type: "CTRL", name: "BMD ATEM 1 M/E Advanced Panel 10", in: ["network"], out: ["network"], details: { me: "1 M/E", conn: "Ethernet" } },
  { id: "bmd-atem-panel-20", cat: "CONTROL PANELS", type: "CTRL", name: "BMD ATEM 2 M/E Advanced Panel 20", in: ["network"], out: ["network"], details: { me: "2 M/E", conn: "Ethernet" } },
  { id: "bmd-atem-panel-40", cat: "CONTROL PANELS", type: "CTRL", name: "BMD ATEM 4 M/E Advanced Panel 40", in: ["network"], out: ["network"], details: { me: "4 M/E", conn: "Ethernet" } },
  { id: "bmd-atem-camera-panel", cat: "CONTROL PANELS", type: "CTRL", name: "BMD ATEM Camera Control Panel", in: ["network"], out: ["network"], details: { panel: "CCU", conn: "Ethernet" } },
  { id: "bmd-atem-micro-camera-panel", cat: "CONTROL PANELS", type: "CTRL", name: "BMD ATEM Micro Camera Panel", in: ["network"], out: ["network"], details: { panel: "CCU", conn: "Ethernet" } },
  { id: "bmd-atem-monitor-panel-20", cat: "CONTROL PANELS", type: "CTRL", name: "BMD ATEM Monitoring Rack Panel 20", in: ["network"], out: ["network"], details: { panel: "Monitoring", conn: "Ethernet" } },
  { id: "bmd-atem-monitor-panel-40", cat: "CONTROL PANELS", type: "CTRL", name: "BMD ATEM Monitoring Rack Panel 40", in: ["network"], out: ["network"], details: { panel: "Monitoring", conn: "Ethernet" } },
  { id: "bmd-hyperdeck-extreme-ctrl", cat: "CONTROL PANELS", type: "CTRL", name: "BMD HyperDeck Extreme Control", in: ["network"], out: ["network"], details: { panel: "Deck control", conn: "RS-422" } },
  { id: "bmd-videohub-smart-control", cat: "CONTROL PANELS", type: "CTRL", name: "BMD Videohub Smart Control Pro", in: ["network"], out: ["network"], details: { buttons: "48", conn: "Ethernet" } },
  { id: "bmd-videohub-master-control", cat: "CONTROL PANELS", type: "CTRL", name: "BMD Videohub Master Control Pro", in: ["network"], out: ["network"], details: { panel: "Master control", conn: "Ethernet" } },

  { id: "bmd-audio-monitor-12g", cat: "AUDIO", type: "AUDIO", name: "BMD Audio Monitor 12G G3", in: ["audio", "video"], details: { ru: "1", format: "12G-SDI" } },

  { id: "bmd-ethernet-switch-360p", cat: "NETWORK", type: "NETWORK", name: "BMD Ethernet Switch 360P", in: ["network"], out: ["network"], details: { ports: "16×10GbE", uplink: "2×100G" } },
  { id: "bmd-ethernet-switch-820", cat: "NETWORK", type: "NETWORK", name: "BMD Ethernet Switch 820", in: ["network"], out: ["network"], details: { ports: "8×100G QSFP", uplink: "2×10GbE" } },

  // ─── Novastar ───

  { id: "nova-vx400", cat: "PROCESSORS", type: "PROC", name: "Novastar VX400", in: ["video"], out: ["network"], details: { ports: "4×RJ45", load: "0%" } },
  { id: "nova-vx600", cat: "PROCESSORS", type: "PROC", name: "Novastar VX600", in: ["video"], out: ["network"], details: { ports: "6×RJ45", load: "0%" } },
  { id: "nova-vx1000", cat: "PROCESSORS", type: "PROC", name: "Novastar VX1000", in: ["video"], out: ["network"], details: { ports: "10×RJ45", load: "0%" } },
  { id: "nova-vx16s", cat: "PROCESSORS", type: "PROC", name: "Novastar VX16s", in: ["video"], out: ["network"], details: { ports: "16×RJ45", load: "0%" } },
  { id: "nova-vx400-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar VX400 Pro", in: ["video"], out: ["network"], details: { ports: "4×RJ45", load: "0%" } },
  { id: "nova-vx600-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar VX600 Pro", in: ["video"], out: ["network"], details: { ports: "6×RJ45", load: "0%" } },
  { id: "nova-vx1000-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar VX1000 Pro", in: ["video"], out: ["network"], details: { ports: "10×RJ45", load: "0%" } },
  { id: "nova-vx2000-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar VX2000 Pro", in: ["video"], out: ["network"], details: { ports: "20×RJ45", load: "0%" } },
  { id: "nova-mx20", cat: "PROCESSORS", type: "PROC", name: "Novastar MX20", in: ["video"], out: ["network"], details: { sys: "COEX/VMP", load: "0%" } },
  { id: "nova-mx30", cat: "PROCESSORS", type: "PROC", name: "Novastar MX30", in: ["video"], out: ["network"], details: { sys: "COEX/VMP", load: "0%" } },
  { id: "nova-mx40-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar MX40 Pro", in: ["video"], out: ["network"], details: { ports: "20×RJ45", load: "0%" } },
  { id: "nova-mx2000-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar MX2000 Pro", in: ["video"], out: ["network"], details: { sys: "COEX/VMP", load: "0%" } },
  { id: "nova-mx6000-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar MX6000 Pro", in: ["video"], out: ["network"], details: { sys: "COEX/VMP", load: "0%" } },
  { id: "nova-cx40-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar CX40 Pro", in: ["video"], out: ["network"], details: { class: "4K", out: "5G / 40G fiber" } },
  { id: "nova-cx80-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar CX80 Pro", in: ["video"], out: ["network"], details: { class: "8K", out: "5G RJ45" } },
  { id: "nova-mctrl-r5", cat: "PROCESSORS", type: "PROC", name: "Novastar MCTRL R5", in: ["video"], out: ["network"], details: { class: "4K", load: "0%" } },
  { id: "nova-mctrl-4k", cat: "PROCESSORS", type: "PROC", name: "Novastar MCTRL 4K", in: ["video"], out: ["network"], details: { ports: "16×RJ45", load: "0%" } },
  { id: "nova-mctrl700", cat: "PROCESSORS", type: "PROC", name: "Novastar MCTRL700", in: ["video"], out: ["network"], details: { ports: "6×RJ45", load: "0%" } },
  { id: "nova-mctrl660-pro", cat: "PROCESSORS", type: "PROC", name: "Novastar MCTRL660 PRO", in: ["video"], out: ["network"], details: { ports: "6×RJ45", load: "0%" } },
  { id: "nova-mctrl660", cat: "PROCESSORS", type: "PROC", name: "Novastar MCTRL660", in: ["video"], out: ["network"], details: { ports: "6×RJ45", load: "0%" } },
  { id: "nova-mctrl600", cat: "PROCESSORS", type: "PROC", name: "Novastar MCTRL600", in: ["video"], out: ["network"], details: { ports: "4×RJ45", load: "0%" } },
  { id: "nova-mctrl300", cat: "PROCESSORS", type: "PROC", name: "Novastar MCTRL300", in: ["video"], out: ["network"], details: { ports: "2×RJ45", load: "0%" } },
  { id: "nova-msd300", cat: "PROCESSORS", type: "PROC", name: "Novastar MSD300", in: ["video"], out: ["network"], details: { ports: "2×RJ45", load: "0%" } },
  { id: "nova-h2", cat: "PROCESSORS", type: "PROC", name: "Novastar H2", in: ["video"], out: ["network"], details: { slots: "2", px: "41.6M" } },
  { id: "nova-h5", cat: "PROCESSORS", type: "PROC", name: "Novastar H5", in: ["video"], out: ["network"], details: { slots: "5", px: "104M" } },
  { id: "nova-h9", cat: "PROCESSORS", type: "PROC", name: "Novastar H9", in: ["video"], out: ["network"], details: { slots: "9", px: "187M" } },
  { id: "nova-h15", cat: "PROCESSORS", type: "PROC", name: "Novastar H15", in: ["video"], out: ["network"], details: { slots: "15", px: "312M" } },
  { id: "nova-h20", cat: "PROCESSORS", type: "PROC", name: "Novastar H20", in: ["video"], out: ["network"], details: { slots: "20", px: "416M" } },

  { id: "nova-et1s-g", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar ET1S-G", out: ["video", "network"], details: { res: "4K", sys: "Kompass FX" } },
  { id: "nova-et2s-g", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar ET2S-G", out: ["video", "network"], details: { res: "4K", sys: "Kompass FX" } },
  { id: "nova-et4s-g", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar ET4S-G", out: ["video", "network"], details: { res: "4K", sys: "Kompass FX" } },
  { id: "nova-et16s-g", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar ET16S-G", out: ["video", "network"], details: { res: "4K", sys: "Kompass FX" } },
  { id: "nova-vunit-3000", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar Vunit 3000", out: ["video", "network"], details: { res: "4K", sys: "VMP" } },
  { id: "nova-mbox600-pro", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar MBOX600 Pro", out: ["video", "network"], details: { res: "4K", sys: "Nova Cloud" } },
  { id: "nova-tu4k-pro", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar TU4K Pro", out: ["video", "network"], details: { res: "4K", sys: "Nova Cloud" } },
  { id: "nova-tb10-plus", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar TB10 Plus", out: ["video", "network"], details: { res: "HD", sys: "Taurus" } },
  { id: "nova-tb20-plus", cat: "VIDEO SOURCES", type: "SOURCE", name: "Novastar TB20 Plus", out: ["video", "network"], details: { res: "HD", sys: "Taurus" } },

  { id: "nova-a5s-plus", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar A5s Plus", in: ["network"], out: ["network"], details: { series: "Armor", data: "1G" } },
  { id: "nova-a7s-plus", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar A7s Plus", in: ["network"], out: ["network"], details: { series: "Armor", data: "1G" } },
  { id: "nova-a8s-n", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar A8s-N", in: ["network"], out: ["network"], details: { series: "Armor", data: "1G" } },
  { id: "nova-a10s-plus-n", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar A10s Plus-N", in: ["network"], out: ["network"], details: { series: "Armor", data: "1G" } },
  { id: "nova-a10s-pro", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar A10s Pro", in: ["network"], out: ["network"], details: { series: "Armor", data: "1G" } },
  { id: "nova-ca50e", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar CA50E", in: ["network"], out: ["network"], details: { px: "768×512", data: "5G" } },
  { id: "nova-mrv208", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar MRV208-1", in: ["network"], out: ["network"], details: { series: "MRV", data: "1G" } },
  { id: "nova-mrv412", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar MRV412", in: ["network"], out: ["network"], details: { series: "MRV", data: "1G" } },
  { id: "nova-mrv416", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar MRV416", in: ["network"], out: ["network"], details: { series: "MRV", data: "1G" } },
  { id: "nova-mrv532", cat: "RECEIVER CARDS", type: "RCV", name: "Novastar MRV532", in: ["network"], out: ["network"], details: { series: "MRV", data: "1G" } },

  { id: "nova-cvt4k-s", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT4K-S", in: ["network"], out: ["network"], details: { fiber: "single-mode", data: "1G" } },
  { id: "nova-cvt4k-m", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT4K-M", in: ["network"], out: ["network"], details: { fiber: "multi-mode", data: "1G" } },
  { id: "nova-cvt10-s", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT10-S", in: ["network"], out: ["network"], details: { fiber: "single-mode", data: "1G" } },
  { id: "nova-cvt10-m", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT10-M", in: ["network"], out: ["network"], details: { fiber: "multi-mode", data: "1G" } },
  { id: "nova-cvt10-pro-s", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT10 Pro-S", in: ["network"], out: ["network"], details: { fiber: "single-mode", data: "1G" } },
  { id: "nova-cvt10-pro-m", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT10 Pro-M", in: ["network"], out: ["network"], details: { fiber: "multi-mode", data: "1G" } },
  { id: "nova-cvt8-5gs", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT8-5GS", in: ["network"], out: ["network"], details: { fiber: "single-mode", data: "5G" } },
  { id: "nova-cvt8-5gm", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT8-5GM", in: ["network"], out: ["network"], details: { fiber: "multi-mode", data: "5G" } },
  { id: "nova-cvt310", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT310", in: ["network"], out: ["network"], details: { fiber: "single-mode", data: "1G" } },
  { id: "nova-cvt320", cat: "CONVERTERS", type: "CONV", name: "Novastar CVT320", in: ["network"], out: ["network"], details: { fiber: "single-mode", data: "1G" } },

  { id: "nova-ku20", cat: "CONTROL PANELS", type: "CTRL", name: "Novastar KU20", in: ["network"], out: ["network"], details: { panel: "COEX console", conn: "Ethernet" } },
];

// Live merged palette (built-in + user additions). Reassigned by
// setCustomSystemDefs; ES module live bindings propagate the new array to every
// importer, so the palette and drop handler always see current devices.
export let SYSTEM_DEVICES: SystemDeviceDef[] = SYSTEM_BUILTIN;

export function setCustomSystemDefs(defs: SystemDeviceDef[]) {
  SYSTEM_DEVICES = [...SYSTEM_BUILTIN, ...defs];
}
